-- Creating the schema for the controller of examinations application

-- DEPARTMENT table
CREATE TABLE DEPARTMENT (
    DNO INT PRIMARY KEY,
    DNAME VARCHAR(50) NOT NULL
);

-- BRANCH table
CREATE TABLE BRANCH (
    BCODE VARCHAR(10) PRIMARY KEY,
    BNAME VARCHAR(50) NOT NULL,
    DNO INT NOT NULL,
    FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNO)
);

-- STUDENT table
CREATE TABLE STUDENT (
    ROLLNO VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    DOB DATE NOT NULL,
    GENDER CHAR(1) NOT NULL,
    DOA DATE NOT NULL,
    BCODE VARCHAR(10) NOT NULL,
    FOREIGN KEY (BCODE) REFERENCES BRANCH(BCODE),
    CONSTRAINT CHK_GENDER CHECK (GENDER IN ('M', 'F', 'O'))
);

-- COURSE table
CREATE TABLE COURSE (
    CCODE VARCHAR(10) PRIMARY KEY,
    CNAME VARCHAR(50) NOT NULL,
    CREDITS INT NOT NULL,
    DNO INT NOT NULL,
    FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNO),
    CONSTRAINT CHK_CREDITS CHECK (CREDITS > 0)
);

-- BRANCH_COURSE table
CREATE TABLE BRANCH_COURSE (
    BCODE VARCHAR(10) NOT NULL,
    CCODE VARCHAR(10) NOT NULL,
    SEMESTER INT NOT NULL,
    PRIMARY KEY (BCODE, CCODE),
    FOREIGN KEY (BCODE) REFERENCES BRANCH(BCODE),
    FOREIGN KEY (CCODE) REFERENCES COURSE(CCODE),
    CONSTRAINT CHK_SEMESTER CHECK (SEMESTER BETWEEN 1 AND 8)
);

-- PREREQUISITE_COURSE table
CREATE TABLE PREREQUISITE_COURSE (
    CCODE VARCHAR(10) NOT NULL,
    PCCODE VARCHAR(10) NOT NULL,
    PRIMARY KEY (CCODE, PCCODE),
    FOREIGN KEY (CCODE) REFERENCES COURSE(CCODE),
    FOREIGN KEY (PCCODE) REFERENCES COURSE(CCODE),
    CONSTRAINT CHK_DIFF_COURSES CHECK (CCODE <> PCCODE)
);

-- ENROLLS table
CREATE TABLE ENROLLS (
    ROLLNO VARCHAR(10) NOT NULL,
    CCODE VARCHAR(10) NOT NULL,
    SESS VARCHAR(20) NOT NULL,
    GRADE CHAR(1) NOT NULL,
    PRIMARY KEY (ROLLNO, CCODE, SESS),
    FOREIGN KEY (ROLLNO) REFERENCES STUDENT(ROLLNO),
    FOREIGN KEY (CCODE) REFERENCES COURSE(CCODE),
    CONSTRAINT CHK_GRADE CHECK (GRADE IN ('S', 'A', 'B', 'C', 'D', 'E', 'U'))
);
