-- Create DEPT table
CREATE TABLE DEPT (
    DEPTNO INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

-- Create STAFF table
CREATE TABLE STAFF (
    STAFFNO INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    DOB DATE NOT NULL,
    GENDER CHAR(1) NOT NULL,
    DOJ DATE NOT NULL,
    DESIGNATION VARCHAR(50) NOT NULL,
    BASIC_PAY DECIMAL(10, 2) NOT NULL,
    DEPTNO INT NOT NULL,
    CONSTRAINT fk_staff_dept FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO),
    CONSTRAINT chk_gender CHECK (GENDER IN ('M', 'F'))
);

-- Create SKILL table
CREATE TABLE SKILL (
    SKILL_CODE INT PRIMARY KEY,
    DESCRIPTION VARCHAR(100) NOT NULL,
    CHARGE_OUTRATE DECIMAL(10, 2) NOT NULL
);

-- Create STAFF_SKILL table
CREATE TABLE STAFF_SKILL (
    STAFFNO INT,
    SKILL_CODE INT,
    PRIMARY KEY (STAFFNO, SKILL_CODE),
    CONSTRAINT fk_staff_skill_staff FOREIGN KEY (STAFFNO) REFERENCES STAFF(STAFFNO),
    CONSTRAINT fk_staff_skill_skill FOREIGN KEY (SKILL_CODE) REFERENCES SKILL(SKILL_CODE)
);

-- Create PROJECT table
CREATE TABLE PROJECT (
    PROJECTNO INT PRIMARY KEY,
    PNAME VARCHAR(100) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    BUDGET DECIMAL(15, 2) NOT NULL,
    PROJECT_MANAGER_STAFFNO INT NOT NULL,
    CONSTRAINT fk_project_staff FOREIGN KEY (PROJECT_MANAGER_STAFFNO) REFERENCES STAFF(STAFFNO),
    CONSTRAINT chk_project_dates CHECK (END_DATE IS NULL OR END_DATE >= START_DATE)
);

-- Create WORKS table
CREATE TABLE WORKS (
    STAFFNO INT,
    PROJECTNO INT,
    DATE_WORKED_ON DATE NOT NULL,
    IN_TIME TIME NOT NULL,
    OUT_TIME TIME NOT NULL,
    PRIMARY KEY (STAFFNO, PROJECTNO, DATE_WORKED_ON),
    CONSTRAINT fk_works_staff FOREIGN KEY (STAFFNO) REFERENCES STAFF(STAFFNO),
    CONSTRAINT fk_works_project FOREIGN KEY (PROJECTNO) REFERENCES PROJECT(PROJECTNO),
    CONSTRAINT chk_work_times CHECK (OUT_TIME > IN_TIME)
);
