CREATE TABLE EMPLOYEE_TABLE (ID NUMBER PRIMARY KEY, EMP_NAME VARCHAR(50), DESIGNATION VARCHAR(100));

INSERT ALL INTO EMPLOYEE_TABLE (ID, EMP_NAME, DESIGNATION) VALUES('0001', 'Princy W', 'SDE1') 
INTO EMPLOYEE_TABLE(ID, EMP_NAME, DESIGNATION) VALUES('0021','Sangeetha', 'SDE2') SELECT * FROM DUAL;

ALTER TABLE EMPLOYEE_TABLE MODIFY (EMP_NAME VARCHAR(50) NOT NULL);

ALTER TABLE EMPLOYEE_TABLE ADD GENDER VARCHAR(1);

ALTER TABLE EMPLOYEE_TABLE ADD CONSTRAINT GENDER_CHECK CHECK (GENDER IN ('M', 'F', 'O'));

UPDATE EMPLOYEE_TABLE SET GENDER = 'F' WHERE EMP_NAME = 'Princy W';

DELETE FROM EMPLOYEE_TABLE WHERE EMP_NAME='Princy W';

RENAME EMPLOYEE_TABLE TO STAFFS;

ALTER TABLE STAFFS RENAME COLUMN EMP_NAME TO NAME;
